# Cirrus yaml script to configure continous integration
#
# Author: Dan Bailey

# Global default configuration
container:
  image: node:latest

# Search the git repository for any trailing spaces
trailing_spaces_task:
  test_script:
    - git grep -n -I -E '^.+[ ]+$'
    - test $? -eq 1

# Search the C++ source code for any tabs
spaces_not_tabs_task:
  test_script:
    - git grep -n "	" -- '*.cc' '*.h'
    - test $? -eq 1
