
coverage:
  range: 50..100
  round: down
  precision: 1

  ignore:
    - openvdb/cmd
    - openvdb/doc
    - openvdb/python
    - openvdb/unittest
    - openvdb/viewer
    - cmd
    - doc
    - python
    - unittest
    - viewer
