
resources:
  containers:
  - container: vfx2019
    image: openvdb/vfx2019:latest
  - container: vfx2018
    image: openvdb/vfx2018:latest
  - container: vfx2017
    image: openvdb/vfx2017:latest
  - container: houdini
    image: danrbailey/openvdb-houdini:latest
    endpoint: danrbailey_docker # private repo to store Houdini installs

stages:
- stage: Build
  jobs:
  - job: testabi6
    pool:
      vmImage: 'ubuntu-16.04'
    container: vfx2019
    timeoutInMinutes: 0
    steps:
    - bash: ci/build.sh clang++ Release 6 ON
    - bash: ./build/openvdb/unittest/vdb_test -v

  - job: testabi5
    pool:
      vmImage: 'ubuntu-16.04'
    container: vfx2018
    timeoutInMinutes: 0
    steps:
    - bash: ci/build.sh clang++ Release 5 ON
    - bash: ./build/openvdb/unittest/vdb_test -v

  - job: testabi4
    pool:
      vmImage: 'ubuntu-16.04'
    container: vfx2017
    timeoutInMinutes: 0
    steps:
    - bash: ci/build.sh clang++ Release 4 ON
    - bash: ./build/openvdb/unittest/vdb_test -v

  - job: testhou175
    pool:
      vmImage: 'ubuntu-16.04'
    container: houdini
    timeoutInMinutes: 0
    steps:
    - bash: ci/build_houdini.sh 17.5 clang++ Release ON

  - job: testhou170
    pool:
      vmImage: 'ubuntu-16.04'
    container: houdini
    timeoutInMinutes: 0
    steps:
    - bash: ci/build_houdini.sh 17.0 clang++ Release OFF

  - job: testhou165
    pool:
      vmImage: 'ubuntu-16.04'
    container: houdini
    timeoutInMinutes: 0
    steps:
    - bash: ci/build_houdini.sh 16.5 clang++ Release OFF

  - job: testabi6noblosc
    pool:
      vmImage: 'ubuntu-16.04'
    container: vfx2019
    timeoutInMinutes: 0
    steps:
    - bash: ci/build.sh clang++ Release 6 OFF
    - bash: ./build/openvdb/unittest/vdb_test -v

  - job: testhou175gcc
    pool:
      vmImage: 'ubuntu-16.04'
    container: houdini
    timeoutInMinutes: 0
    steps:
    - bash: ci/build_houdini.sh 17.5 g++ Release OFF

  - job: testhou175debug
    pool:
      vmImage: 'ubuntu-16.04'
    container: houdini
    timeoutInMinutes: 0
    steps:
    - bash: ci/build_houdini.sh 17.5 clang++ Debug OFF

  - job: testabi6gcc
    pool:
      vmImage: 'ubuntu-16.04'
    container: vfx2019
    timeoutInMinutes: 0
    steps:
    - bash: ci/build.sh g++ Release 6 ON

  - job: testabi6debug
    pool:
      vmImage: 'ubuntu-16.04'
    container: vfx2019
    timeoutInMinutes: 0
    steps:
    - bash: ci/build.sh clang++ Debug 6 ON
