
resources:
  containers:
  - container: houtest
    image: danrbailey/openvdb-houdini:latest
    endpoint: danrbailey_docker

stages:
- stage: Build
  jobs:
  - job: testhou175
    pool:
      vmImage: 'ubuntu-16.04'
    container: houtest
    timeoutInMinutes: 0
    steps:
    - bash: ci/build_houdini.sh clang++ Release ON
