
# Default configuration

defaults: &defaults
  docker:
    - image: debian:stretch

# Install Aliases

_install: &install
  name: Install
  command: bash ci/install.sh

_cmake:
  cmake_latest: &install_cmake_latest
    name: Install CMake Latest
    command: bash ci/install_cmake.sh latest
  cmake3_11: &install_cmake3_11
    name: Install CMake 3.11
    command: bash ci/install_cmake.sh 3.11.4

_boost:
  boost_latest: &install_boost_latest
    name: Install Boost Latest
    command: bash ci/install_boost.sh latest
  boost1_66: &install_boost1_66
    name: Install Boost 1.66
    command: bash ci/install_boost.sh 1.66.0
  boost1_61: &install_boost1_61
    name: Install Boost 1.61
    command: bash ci/install_boost.sh 1.61.0

_openexr:
  openexr_latest: &install_openexr_latest
    name: Install OpenEXR Latest
    command: bash ci/install_openexr.sh latest
  openexr2_3: &install_openexr2_3
    name: Install OpenEXR 2.3.0
    command: bash ci/install_openexr.sh 2.3.0
  openexr2_2: &install_openexr2_2
    name: Install OpenEXR 2.2.0
    command: bash ci/install_openexr.sh 2.2.0

_tbb:
  tbb_latest: &install_tbb_latest
    name: Install TBB Latest
    command: bash ci/install_tbb.sh latest
  tbb2018: &install_tbb2018
    name: Install TBB 2018
    command: bash ci/install_tbb.sh 2018
  tbb2017: &install_tbb2017
    name: Install TBB 2017
    command: bash ci/install_tbb.sh 2017_U6
  tbb4_4: &install_tbb4_4
    name: Install TBB 4.4
    command: bash ci/install_tbb.sh 4.4

_blosc:
  blosc_latest: &install_blosc_latest
    name: Install Blosc Latest
    command: bash ci/install_blosc.sh latest
  blosc1_5: &install_blosc1_5
    name: Install Blosc 1.5.0
    command: bash ci/install_blosc.sh 1.5.0

_houdini:
  houdini17_5: &install_houdini17_5
    name: Install Houdini 17.5
    command: bash ci/install_houdini.sh 17.5
  houdini17_0: &install_houdini17_0
    name: Install Houdini 17.0
    command: bash ci/install_houdini.sh 17.0
  houdini16_5: &install_houdini16_5
    name: Install Houdini 16.5
    command: bash ci/install_houdini.sh 16.5

# Build and Test Aliases

_build_core:
  abi6: &build_abi6
    name: Build ABI 6
    command: bash ci/build.sh clang++ Release 6 ON
  abi5: &build_abi5
    name: Build ABI 5
    command: bash ci/build.sh clang++ Release 5 ON
  abi4: &build_abi4
    name: Build ABI 4
    command: bash ci/build.sh clang++ Release 4 ON
  abi6_debug: &build_abi6_debug
    name: Build ABI 6 (Debug)
    command: bash ci/build.sh clang++ Debug 6 ON
  abi6_gcc: &build_abi6_gcc
    name: Build ABI 6 (GCC)
    command: bash ci/build.sh g++ Release 6 ON
  abi6_no_blosc: &build_abi6_no_blosc
    name: Build ABI 6 (No Blosc)
    command: bash ci/build.sh clang++ Release 6 OFF

_build_houdini:
  houdini: &build_houdini
    name: Build Houdini
    command: bash ci/build_houdini.sh clang++ Release OFF
    no_output_timeout: 1200
  houdini_al: &build_houdini_all
    name: Build Houdini
    command: bash ci/build_houdini.sh clang++ Release ON
    no_output_timeout: 1200
  houdini_debug: &build_houdini_debug
    name: Build Houdini (Debug)
    command: bash ci/build_houdini.sh clang++ Debug OFF
    no_output_timeout: 1200
  houdini_gcc: &build_houdini_gcc
    name: Build Houdini (GCC)
    command: bash ci/build_houdini.sh g++ Release OFF
    no_output_timeout: 1200

_test:
  test: &test
    name: Unit Tests
    command: ./build/openvdb/unittest/vdb_test -v

# Jobs

# TODO: testabi5, testabi4, testhou175 need OpenEXR makefile support for 2.2

version: 2.1
jobs:
  testblosclatest:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: *install_blosc_latest
      - run: *build_abi6
      - run: *test

  testblosc150:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.5.0
      - run: *build_abi6
      - run: *test

  testblosc151:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.5.1
      - run: *build_abi6
      - run: *test

  testblosc152:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.5.2
      - run: *build_abi6
      - run: *test

  testblosc153:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.5.3
      - run: *build_abi6
      - run: *test

  testblosc154:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.5.4
      - run: *build_abi6
      - run: *test

  testblosc160:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.6.0
      - run: *build_abi6
      - run: *test

  testblosc161:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.6.1
      - run: *build_abi6
      - run: *test

  testblosc170:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.7.0
      - run: *build_abi6
      - run: *test

  testblosc171:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.7.1
      - run: *build_abi6
      - run: *test

  testblosc180:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.8.0
      - run: *build_abi6
      - run: *test

  testblosc181:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.8.1
      - run: *build_abi6
      - run: *test

  testblosc190:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.9.0
      - run: *build_abi6
      - run: *test

  testblosc1100:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.10.0
      - run: *build_abi6
      - run: *test

  testblosc1101:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.10.1
      - run: *build_abi6
      - run: *test

  testblosc1102:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.10.2
      - run: *build_abi6
      - run: *test

  testblosc1110:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.11.0
      - run: *build_abi6
      - run: *test

  testblosc1111:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.11.1
      - run: *build_abi6
      - run: *test

  testblosc1112:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.11.2
      - run: *build_abi6
      - run: *test

  testblosc1113:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.11.3
      - run: *build_abi6
      - run: *test

  testblosc1120:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.12.0
      - run: *build_abi6
      - run: *test

  testblosc1121:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.12.1
      - run: *build_abi6
      - run: *test

  testblosc1130:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.13.0
      - run: *build_abi6
      - run: *test

  testblosc1131:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.13.1
      - run: *build_abi6
      - run: *test

  testblosc1132:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.13.2
      - run: *build_abi6
      - run: *test

  testblosc1133:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.13.3
      - run: *build_abi6
      - run: *test

  testblosc1134:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.13.4
      - run: *build_abi6
      - run: *test

  testblosc1135:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.13.5
      - run: *build_abi6
      - run: *test

  testblosc1136:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.13.6
      - run: *build_abi6
      - run: *test

  testblosc1137:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.13.7
      - run: *build_abi6
      - run: *test

  testblosc1140:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.14.0
      - run: *build_abi6
      - run: *test

  testblosc1141:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.14.1
      - run: *build_abi6
      - run: *test

  testblosc1142:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.14.2
      - run: *build_abi6
      - run: *test

  testblosc1143:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.14.3
      - run: *build_abi6
      - run: *test

  testblosc1144:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.14.4
      - run: *build_abi6
      - run: *test

  testblosc1150:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.15.0
      - run: *build_abi6
      - run: *test

  testblosc1160:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.16.0
      - run: *build_abi6
      - run: *test

  testblosc1161:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.16.1
      - run: *build_abi6
      - run: *test

  testblosc1162:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.16.2
      - run: *build_abi6
      - run: *test

  testblosc1163:
    <<: *defaults
    steps:
      - checkout
      - run: *install
      - run: *install_cmake3_11
      - run: *install_boost1_66
      - run: *install_tbb2018
      - run: *install_openexr2_3
      - run: bash ci/install_blosc.sh 1.16.3
      - run: *build_abi6
      - run: *test

# Workflows

workflows:
  build_and_test:
    jobs:
      - testblosclatest
      - testblosc150
      - testblosc151
      - testblosc152
      - testblosc153
      - testblosc154
      - testblosc160
      - testblosc161
      - testblosc170
      - testblosc171
      - testblosc180
      - testblosc181
      - testblosc190
      - testblosc1100
      - testblosc1101
      - testblosc1102
      - testblosc1110
      - testblosc1111
      - testblosc1112
      - testblosc1113
      - testblosc1120
      - testblosc1121
      - testblosc1130
      - testblosc1131
      - testblosc1132
      - testblosc1133
      - testblosc1134
      - testblosc1135
      - testblosc1136
      - testblosc1137
      - testblosc1140
      - testblosc1141
      - testblosc1142
      - testblosc1143
      - testblosc1144
      - testblosc1150
      - testblosc1160
      - testblosc1161
      - testblosc1162
      - testblosc1163

