
name: Build

on:
  push:
    branches:
      - 'master'
      - 'feature/**'
      - 'pr/**'
    paths-ignore:
      - 'CHANGES'
      - 'CODEOWNERS'
      - 'doc/**'
      - 'openvdb_maya/**'
      - 'openvdb_houdini/**'
      - 'openvdb_ax/**'
      - 'nanovdb/**'
      - 'pendingchanges/**'
      - '**.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'CHANGES'
      - 'CODEOWNERS'
      - 'doc/**'
      - 'openvdb_maya/**'
      - 'openvdb_houdini/**'
      - 'openvdb_ax/**'
      - 'nanovdb/**'
      - 'pendingchanges/**'
      - '**.md'
  schedule:
    # run this workflow every day at 7am UTC except Monday
    - cron:  '0 7 * * 0,2-6'
    # run this workflow Monday 7am UTC
    # warning: This pattern is checked in various places below
    - cron:  '0 7 * * 1'
  workflow_dispatch:
    inputs:
      type:
        description: 'The type of CI to run (all, linux, win, mac)'
        required: true
        default: 'all'

jobs:
  # Extra compiler tests
  linux-cxx17:
    if: |
      github.event_name != 'workflow_dispatch' ||
      github.event.inputs.type == 'all' ||
      github.event.inputs.type == 'extra'
    runs-on: ubuntu-20.04
    name: linux-cxx17:${{ matrix.config.cxx }}
    env:
      CXX: ${{ matrix.config.cxx }}
    strategy:
      matrix:
        config:
          - { cxx: 'g++-10',     j: '1' }
          - { cxx: 'clang++-10', j: '2' }
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: update_apt
      run: sudo apt-get update
    - name: install
      run: >
        sudo apt-get -q install -y
        libboost-dev libboost-system-dev libboost-iostreams-dev libboost-python-dev
        libglfw3-dev libtbb-dev libgtest-dev libcppunit-dev libglu1-mesa-dev
    - name: build
      run: >
        ./ci/build.sh -v
        --build-type=Release
        -j ${{ matrix.config.j }}
        --components=\"core,python,test,bin,view,render,axcore,axbin,axtest\"
        --cargs=\"
        -DUSE_BLOSC=OFF
        -DCMAKE_CXX_STANDARD=17
        -DOPENVDB_ABI_VERSION_NUMBER=9
        -DCMAKE_INSTALL_PREFIX=`pwd`
        \"
    - name: test
      run: cd build && ctest -V
