
name: Target

on:
  push:
    branches:
      - '**'
  pull_request_target:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      shell: bash
      run: echo "${{ github.event_name }}"
